/* Generated by            cobc 2.0.20131031 */
/* Generated from              gnucobol-fastcgi-sample.cbl */
/* Generated at                Sep 13 2016 06:14:08 */
/* GNU Cobol C++ build date    May 16 2016 14:03:52 */
/* GNU Cobol C++ package date  May 03 2014 21:13:34 UTC */
/* Compile command         cobc -x -C gnucobol-fastcgi-sample.cbl */

/* Program local variables for 'gnucobol-fastcgi-sample' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File webinput */
static cob_file		*_h_WEBINPUT = NULL;
static unsigned char	_h_WEBINPUT_status[4];

/* Local cob_field items */
cob_field		_f0(0, 0, 0);
cob_field		_f1(0, 0, 0);


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	* _frame_ptr;
struct cob_frame	_frame_stack[255];


/* Data storage */
static int       RETURN_CODE;	// RETURN-CODE
static cob_u8_t  _b_6[1024];	// webinput Record
#pragma pack(push, 1)
static struct _s1_CURRENT_TIME_RAW {
	cob_u8_t  CT_HOURS[2];	// ct-hours
	cob_u8_t  CT_MINUTES[2];	// ct-minutes
	cob_u8_t  CT_SECONDS[2];	// ct-seconds
	cob_u8_t  CT_HUNDREDTHS[2];	// ct-hundredths
} CURRENT_TIME_RAW;	// current-time-raw
#pragma pack(pop)
#pragma pack(push, 1)
static struct _s2_CURRENT_TIME {
	cob_u8_t  CT_HOURS[2];	// ct-hours
	cob_u8_t  FILLER_1[1];	// FILLER 1
	cob_u8_t  CT_MINUTES[2];	// ct-minutes
	cob_u8_t  FILLER_2[1];	// FILLER 2
	cob_u8_t  CT_SECONDS[2];	// ct-seconds
	cob_u8_t  FILLER_3[1];	// FILLER 3
	cob_u8_t  CT_HUNDREDTHS[2];	// ct-hundredths
} CURRENT_TIME;	// current-time
#pragma pack(pop)
static cob_u8_t  FASTCGI_ACCEPT[4];	// fastcgi-accept
static cob_u8_t  NEWLINE[1];	// newline
static cob_u8_t  NAME_INDEX[1];	// name-index
static cob_u8_t  VALUE_STRING[256];	// value-string
#pragma pack(push, 1)
static struct _s3_ENVIRONMENT_NAMES {
	union _s4__UN2E2N1 {
		struct _s5_NAME_STRINGS {
			cob_u8_t  FILLER_4[20];	// FILLER 4
			cob_u8_t  FILLER_5[20];	// FILLER 5
			cob_u8_t  FILLER_6[20];	// FILLER 6
			cob_u8_t  FILLER_7[20];	// FILLER 7
			cob_u8_t  FILLER_8[20];	// FILLER 8
			cob_u8_t  FILLER_9[20];	// FILLER 9
			cob_u8_t  FILLER_10[20];	// FILLER 10
			cob_u8_t  FILLER_11[20];	// FILLER 11
			cob_u8_t  FILLER_12[20];	// FILLER 12
			cob_u8_t  FILLER_13[20];	// FILLER 13
			cob_u8_t  FILLER_14[20];	// FILLER 14
			cob_u8_t  FILLER_15[20];	// FILLER 15
			cob_u8_t  FILLER_16[20];	// FILLER 16
			cob_u8_t  FILLER_17[20];	// FILLER 17
			cob_u8_t  FILLER_18[20];	// FILLER 18
			cob_u8_t  FILLER_19[20];	// FILLER 19
			cob_u8_t  FILLER_20[20];	// FILLER 20
			cob_u8_t  FILLER_21[20];	// FILLER 21
			cob_u8_t  FILLER_22[20];	// FILLER 22
			cob_u8_t  FILLER_23[20];	// FILLER 23
			cob_u8_t  FILLER_24[20];	// FILLER 24
			cob_u8_t  FILLER_25[20];	// FILLER 25
			cob_u8_t  FILLER_26[20];	// FILLER 26
			cob_u8_t  FILLER_27[20];	// FILLER 27
			cob_u8_t  FILLER_28[20];	// FILLER 28
			cob_u8_t  FILLER_29[20];	// FILLER 29
			cob_u8_t  FILLER_30[20];	// FILLER 30
			cob_u8_t  FILLER_31[20];	// FILLER 31
			cob_u8_t  FILLER_32[20];	// FILLER 32
			cob_u8_t  FILLER_33[20];	// FILLER 33
			cob_u8_t  FILLER_34[20];	// FILLER 34
			cob_u8_t  FILLER_35[20];	// FILLER 35
			cob_u8_t  FILLER_36[20];	// FILLER 36
			cob_u8_t  FILLER_37[20];	// FILLER 37
		} NAME_STRINGS;	// name-strings
		struct _s6_FILLER_38 {
			cob_u8_t  NAME_STRING[34][20];	// name-string
		} FILLER_38;	// FILLER 38
	} _UN2E2N1;	// _un2e2n1
} ENVIRONMENT_NAMES;	// environment-names
#pragma pack(pop)

/* End of data storage */


/* Fields */
static cob_field _f_6(1024, _b_6, &_a_5);	/* webinput Record */
static cob_field _f_7(8, (cob_u8_t *)&CURRENT_TIME_RAW, &_a_2);	/* current-time-raw */
static cob_field _f_12(11, (cob_u8_t *)&CURRENT_TIME, &_a_2);	/* current-time */
static cob_field _f_20(4, FASTCGI_ACCEPT, &_a_1);	/* fastcgi-accept */
static cob_field _f_22(1, NEWLINE, &_a_5);	/* newline */
static cob_field _f_24(256, VALUE_STRING, &_a_5);	/* value-string */

/* End of fields */

