/* Generated by           cobc 2.0.0 */
/* Generated from         sample.cbl */
/* Generated at           Sep 23 2016 09:51:15 */
/* GnuCOBOL build date    Sep 23 2016 08:22:08 */
/* GnuCOBOL package date  Aug 14 2016 12:21:51 UTC */
/* Compile command        cobc -x -C sample.cbl */

#include <fcgiapp.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"sample.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 23 2016 09:51:15"
#define  COB_MODULE_DATE		20160923
#define  COB_MODULE_TIME		95115

/* Global variables */
#include "sample.c.h"

/* Function prototypes */

static int		sample ();
static int		sample_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (sample ());
}

/* Functions */

/* PROGRAM-ID 'sample' */

/* ENTRY 'sample' */

static int
sample ()
{
  return sample_ (0);
}

static int
sample_ (const int entry)
{
  /* Program local variables */
  #include "sample.c.l.h"

//AMRESH KADIAN - changes start
  FCGX_Stream *in, *out, *err;
  FCGX_ParamArray envp;
  while (FCGX_Accept(&in, &out, &err, &envp) >= 0) {
    char *q = FCGX_GetParam("QUERY_STRING", envp);
    FCGX_FPrintF(out, "Content-type: text/plain\r\n\r\n");
    if (!q) {
      FCGX_FPrintF(out,
          "no query string: check web server configuration\n");
    };

    FCGX_FPrintF(out, "INSIDE sample_()");
    FCGX_FPrintF(out, "My Simple Query: '%s'\n", q);

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Save number of call params */
  module->module_num_params = cob_glob_ptr->cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 12        : Entry     sample                  : sample.cbl */
  l_2:;

  /* Line: 12        : MOVE               : sample.cbl */
  *(b_6) = 32;

  /* Line: 13        : GOBACK             : sample.cbl */
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  } /* AMRESH KADIAN added line */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "sample";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())sample;
  module->module_cancel.funcptr = (void *(*)())sample_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  cob_set_cancel (module);
  b_1 = 0;
  *(cob_u8_ptr)(b_6) = 32;
  initialized = 1;
  goto P_ret_initialize;
  P_cancel:
  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }
  initialized = 0;
  return 0;
}
