/* Generated by            cobc 1.1.0 */
/* Generated from          b.cbl */
/* Generated at            Sep 22 2016 11:09:20 IST */
/* OpenCOBOL build date    Nov 02 2013 00:16:01 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -m -C b.cbl */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"b.cbl"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "b.c.h"

/* Function prototypes */

int b (unsigned char *);
static int b_ (const int, unsigned char *);

/* Functions */

int
b (unsigned char *b_9)
{
  return b_ (0, b_9);
}

static int
b_ (const int entry, unsigned char *b_9)
{
  /* Local variables */
  #include "b.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      if (module.next)
        cob_set_cancel ((const char *)"b", (void *)b, (void *)b_);
      (*(int *) (b_1)) = 0;
      memset (b_5, 32, 12);
      initialized = 1;
    }

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry b */

  l_2:;

  /* MAIN SECTION */

  /* MAIN-PROCEDURE */

  /* b.cbl:37: INITIALIZE */
  {
    memset (b_5, 32, 12);
  }
  /* b.cbl:38: IF */
  {
    if (((int)cob_cmpswp_s32_binary (b_9, 0) >  0))
      {
        /* b.cbl:39: MOVE */
        {
          memcpy (b_5, b_9 + 4, 12);
        }
        /* b.cbl:41: MOVE */
        {
          memcpy (b_5 + 6, "KADIAN", 6);
        }
        /* b.cbl:43: MOVE */
        {
          memcpy (b_9 + 4, b_5, 12);
        }
      }
    else
      {
        /* b.cbl:46: MOVE */
        {
          memcpy (b_5, "AMRESH", 6);
        }
      }
  }

  /* Program exit */

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));
}

/* End functions */

