/* Generated by            cobc 1.1.0 */
/* Generated from          gnucobol-fastcgi-sample.cob */
/* Generated at            Sep 22 2016 10:27:13 IST */
/* OpenCOBOL build date    Nov 02 2013 00:16:01 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -x -C gnucobol-fastcgi-sample.cob */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Storage */

/* PROGRAM-ID : gnucobol-fastcgi-sample */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_6[1024] __attribute__((aligned));	/* webinput_record */
static unsigned char b_7[8] __attribute__((aligned));	/* current-time-raw */
static unsigned char b_12[11] __attribute__((aligned));	/* current-time */
static unsigned char b_20[4] __attribute__((aligned));	/* fastcgi-accept */
static unsigned char b_22[1] __attribute__((aligned));	/* newline */
static unsigned char b_23[1] __attribute__((aligned));	/* name-index */
static unsigned char b_24[256] __attribute__((aligned));	/* value-string */
static unsigned char b_25[680] __attribute__((aligned));	/* environment-names */

/* End of storage */


/* Attributes */

static const cob_field_attr a_1 = {36, 2, 0, 0, "Z\001\000\000\0009\001\000\000\000"};
static const cob_field_attr a_2 = {33, 0, 0, 0, NULL};
static const cob_field_attr a_3 = {17, 9, 0, 65, NULL};
static const cob_field_attr a_4 = {1, 0, 0, 0, NULL};
static const cob_field_attr a_5 = {16, 2, 0, 0, NULL};

/* Fields */

/* PROGRAM-ID : gnucobol-fastcgi-sample */
static cob_field f_6	= {1024, b_6, &a_2};	/* webinput_record */
static cob_field f_7	= {8, b_7, &a_4};	/* current-time-raw */
static cob_field f_12	= {11, b_12, &a_4};	/* current-time */
static cob_field f_20	= {4, b_20, &a_3};	/* fastcgi-accept */
static cob_field f_22	= {1, b_22, &a_2};	/* newline */
static cob_field f_24	= {256, b_24, &a_2};	/* value-string */

/* End of fields */

/* Constants */
static cob_field c_1	= {40, (unsigned char *)"FCGI_Accept call error, link with -lfcgi", &a_2};
static cob_field c_2	= {23, (unsigned char *)"Content-type: text/html", &a_2};
static cob_field c_3	= {12, (unsigned char *)"<html><body>", &a_2};
static cob_field c_4	= {43, (unsigned char *)"<h3>FastCGI environment with GNU Cobol</h3>", &a_2};
static cob_field c_5	= {53, (unsigned char *)"<a href=\"/gnucobol-fastcgiform.html\">FastCGI form</a>", &a_2};
static cob_field c_6	= {10, (unsigned char *)"<p><table>", &a_2};
static cob_field c_7	= {1, (unsigned char *)"<", &a_2};
static cob_field c_8	= {1, (unsigned char *)" ", &a_2};
static cob_field c_9	= {1, (unsigned char *)">", &a_2};
static cob_field c_10	= {1, (unsigned char *)"&", &a_2};
static cob_field c_11	= {8, (unsigned char *)"<tr><td>", &a_2};
static cob_field c_12	= {11, (unsigned char *)": </td><td>", &a_2};
static cob_field c_13	= {10, (unsigned char *)"</td></tr>", &a_2};
static cob_field c_14	= {14, (unsigned char *)"REQUEST_METHOD", &a_2};
static cob_field c_15	= {4, (unsigned char *)"POST", &a_2};
static cob_field c_16	= {22, (unsigned char *)"<tr><td align=\"right\">", &a_2};
static cob_field c_17	= {29, (unsigned char *)"First chunk of POST:</td><td>", &a_2};
static cob_field c_18	= {12, (unsigned char *)"</table></p>", &a_2};
static cob_field c_19	= {14, (unsigned char *)"Current time: ", &a_2};
static cob_field c_20	= {14, (unsigned char *)"</body></html>", &a_2};

