/* Generated by            cobc 1.1.0 */
/* Generated from          gnucobol-fastcgi-sample.cob */
/* Generated at            Sep 22 2016 10:27:13 IST */
/* OpenCOBOL build date    Nov 02 2013 00:16:01 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -x -C gnucobol-fastcgi-sample.cob */

/* File webinput */
static cob_file		*h_WEBINPUT = NULL;
static unsigned char	h_WEBINPUT_status[4];

/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Call pointers */
static union cob_call_union	call_FCGI_Accept = { NULL };


/* Local cob_field items */
cob_field	f0;
cob_field	f1;

