/* Generated by            cobc 1.1.0 */
/* Generated from          pgm.cbl */
/* Generated at            Sep 22 2016 13:13:40 IST */
/* OpenCOBOL build date    Nov 02 2013 00:16:01 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -m -C pgm.cbl */


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

