/* Generated by            cobc 2.0.20131031 */
/* Generated from              sample.cbl */
/* Generated at                Sep 23 2016 10:14:42 */
/* GNU Cobol C++ build date    May 16 2016 14:03:52 */
/* GNU Cobol C++ package date  May 03 2014 21:13:34 UTC */
/* Compile command         cobc -x -C sample.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Attributes */

static const cob_field_attr _a_1(0x21,   0,   0, 0x0000, NULL);

