/* Generated by            cobc 2.0.20131031 */
/* Generated from              sample.cbl */
/* Generated at                Sep 23 2016 10:14:42 */
/* GNU Cobol C++ build date    May 16 2016 14:03:52 */
/* GNU Cobol C++ package date  May 03 2014 21:13:34 UTC */
/* Compile command         cobc -x -C sample.cbl */

/* Program local variables for 'sample' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
cob_call_union		cob_unifunc;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	* _frame_ptr;
struct cob_frame	_frame_stack[255];


/* Data storage */
static int       RETURN_CODE;	// RETURN-CODE
#pragma pack(push, 1)
static struct _s1_CURRENT_TIME_RAW {
	cob_u8_t  CT_HOURS[2];	// ct-hours
	cob_u8_t  CT_MINUTES[2];	// ct-minutes
	cob_u8_t  CT_SECONDS[2];	// ct-seconds
	cob_u8_t  CT_HUNDREDTHS[2];	// ct-hundredths
} CURRENT_TIME_RAW;	// current-time-raw
#pragma pack(pop)
#pragma pack(push, 1)
static struct _s2_WS_PGM {
	cob_u8_t  WS_PGM_NAME[8];	// ws-pgm-name
} WS_PGM;	// ws-pgm
#pragma pack(pop)

/* End of data storage */


/* Fields */
static cob_field _f_11(8, WS_PGM.WS_PGM_NAME, &_a_1);	/* ws-pgm-name */

/* End of fields */

